# Generated by Django 3.2.4 on 2021-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210610_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='tests', max_length=255),
        ),
    ]
