# Generated by Django 3.2.4 on 2021-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ecology', 'ecology'), ('gardening', 'gardening'), ('botany', 'botany')], max_length=255),
        ),
    ]
